#ifndef DEF_H
#define DEF_H

typedef enum {
    MAIN_WINDOW_STATE_NONE = 0,
    MAIN_WINDOW_STATE_DASHBOARD,
    MAIN_WINDOW_STATE_WALLET,
    MAIN_WINDOW_STATE_STATITICS,
    MAIN_WINDOW_STATE_TRANSITION,
    MAIN_WINDOW_STATE_SWAP,
    MAIN_WINDOW_STATE_LOGOUT
}mainWindowState_e;

#endif // DEF_H
